# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation

check_api:
    path: /api/check_api
    defaults: { _controller: "AppBundle:Default:checkAPI" }

login:
    path: /login
    defaults: { _controller: "AppBundle:Security:login" }