# # To get started with security, check out the documentation:
# # https://symfony.com/doc/current/security.html
# security:

#     # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#     providers:
#         in_memory:
#             memory: ~

#     firewalls:
#         # disables authentication for assets and the profiler, adapt it according to your needs
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false

#         main:
#             anonymous: ~
#             # activate different ways to authenticate
#             logout_on_user_change: true
#             # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#             #http_basic: ~

#             # https://symfony.com/doc/current/security/form_login_setup.html
#             #form_login: ~

security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        app_user_provider:
            entity:
                class: AppBundle\Entity\User
                property: email

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }